#!/usr/bin/env python3
"""Barrot self-upgrade: identify capability gaps, generate a module, verify it,
open a PR. Never pushes to main -- barrot-gated-merge.yml tiers the result."""
import os, json, subprocess, urllib.request, sys, re
from pathlib import Path
from datetime import datetime, timezone

GROQ_KEY = os.environ.get("GROQ_API_KEY", "")
REPO_ROOT = Path(__file__).resolve().parent.parent
SCRIPTS_DIR = REPO_ROOT / "scripts"

BANNED_TERMS = [
    "rm -rf", ".git/", "git reset --hard", "git checkout main", "sed -i",
    "git push", "subprocess.run([\"git\"", "os.system",
    "quantum harmonization", "free energy", "Willowchip", "Aethel",
    "Planck-scale", "bio-computing", "144-agent council",
]

def load_audit():
    f = REPO_ROOT / "barrot_capability_audit.json"
    if not f.exists():
        return None
    with open(f) as fh:
        return json.load(fh)

def call_groq(prompt):
    body = json.dumps({
        "model": "openai/gpt-oss-120b",
        "messages": [{"role": "user", "content": prompt}],
        "max_tokens": 2000,
        "temperature": 0.4,
    }).encode()
    req = urllib.request.Request(
        "https://api.groq.com/openai/v1/chat/completions", data=body,
        headers={"Authorization": f"Bearer {GROQ_KEY}",
                 "Content-Type": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=90) as resp:
            return json.load(resp)["choices"][0]["message"]["content"]
    except Exception as e:
        print(f"Groq error: {e}")
        return ""

def strip_fences(text):
    m = re.search(r"```(?:python)?\s*\n(.*?)```", text, re.S)
    return m.group(1) if m else text

def generate_capability(gap_id, gap_name):
    prompt = f"""Implement this capability as a standalone Python script: {gap_name} (gap ID {gap_id})

HARD CONSTRAINTS:
- stdlib only (os, sys, json, urllib.request, pathlib, datetime, subprocess for read-only checks)
- Call Groq model openai/gpt-oss-120b via urllib for any analysis
- Read GROQ_API_KEY from env; exit non-zero if unset
- Write results to a JSON file; never mutate existing repo files
- NO git commands, NO os.system, NO shell mutation, NO rm
- If real input data is unavailable, write an explicit null/unavailable field.
  NEVER generate placeholder, simulated, or randomized values as if they were results.
- Do not reference hardware, APIs, or database tables you cannot verify exist

Output ONLY the Python source, starting with the shebang."""
    code = strip_fences(call_groq(prompt)).strip()
    if not code.startswith("#!"):
        print("REJECTED: output does not look like a script")
        return None
    for term in BANNED_TERMS:
        if term in code:
            print(f"REJECTED: banned term {term!r} in generated code")
            return None
    for fake in ("random.uniform", "random.random", "random.randint"):
        if fake in code:
            print(f"REJECTED: {fake} -- fabricated-data pattern")
            return None
    return code

def verify_syntax(code):
    tmp = REPO_ROOT / ".selfupgrade_candidate.py"
    tmp.write_text(code)
    r = subprocess.run([sys.executable, "-m", "py_compile", str(tmp)],
                       capture_output=True)
    tmp.unlink(missing_ok=True)
    if r.returncode != 0:
        print(f"REJECTED: syntax error\n{r.stderr.decode()[:400]}")
        return False
    print("Syntax OK")
    return True

def git(*args, check=False):
    return subprocess.run(["git", *args], cwd=REPO_ROOT,
                          capture_output=True, text=True, check=check)

def open_capability_pr(gap_name, code):
    slug = re.sub(r"[^a-z0-9]+", "_", gap_name.lower()).strip("_")[:40]
    target = SCRIPTS_DIR / f"{slug}.py"
    if target.exists():
        print(f"ABORT: {target.name} already exists -- refusing to overwrite")
        return False
    stamp = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
    branch = f"selfupgrade/{slug}-{stamp}"
    git("checkout", "-b", branch)
    target.write_text(code)
    git("add", str(target.relative_to(REPO_ROOT)))
    git("commit", "-m", f"Self-upgrade candidate: {gap_name}")
    push = git("push", "-u", "origin", branch)
    if push.returncode != 0:
        print(f"Push failed: {push.stderr[:300]}")
        return False
    body = (f"Autonomous self-upgrade candidate for gap: **{gap_name}**\n\n"
            "Generated by scripts/barrot_self_upgrade.py. Passed banned-term, "
            "fabricated-data, and syntax checks only. NOT executed. "
            "Requires human review before merge; barrot-gated-merge.yml will "
            "tier this like any other PR.")
    bf = REPO_ROOT / ".selfupgrade_pr_body.md"
    bf.write_text(body)
    pr = subprocess.run(
        ["gh", "pr", "create", "--title", f"Self-upgrade: {gap_name}",
         "--body-file", str(bf), "--base", "main", "--head", branch],
        cwd=REPO_ROOT, capture_output=True, text=True)
    bf.unlink(missing_ok=True)
    print(pr.stdout or pr.stderr)
    git("checkout", "main")
    return pr.returncode == 0

def self_upgrade():
    audit = load_audit()
    if not audit or not audit.get("gaps"):
        print("No capability gaps found")
        return
    gap = audit["gaps"][0]
    print(f"Upgrading: {gap['name']} (id {gap['id']})")
    code = generate_capability(gap["id"], gap["name"])
    if not code or not verify_syntax(code):
        return
    open_capability_pr(gap["name"], code)

if __name__ == "__main__":
    if not GROQ_KEY:
        print("GROQ_API_KEY not set")
        sys.exit(1)
    self_upgrade()
