#!/usr/bin/env python3
"""Dumps the FULL non-error content of workspace.barrot.brain to the repo
for direct human + Claude review. Handles Databricks SQL Statement API
result pagination (chunked results) since ~950+ text rows will not fit
in a single inline response."""
import os, json, time, requests

host = os.environ["DATABRICKS_HOST"]
token = os.environ["DATABRICKS_TOKEN"]
warehouse = os.environ["DATABRICKS_WAREHOUSE_ID"]
HEADERS = {"Authorization": f"Bearer {token}"}

SQL = (
    "SELECT timestamp, topic, insight, session FROM workspace.barrot.brain "
    "WHERE insight NOT LIKE '%error%' AND insight NOT LIKE '%Rate limit%' "
    "ORDER BY topic, timestamp"
)

def execute(sql):
    r = requests.post(
        f"https://{host}/api/2.0/sql/statements",
        headers=HEADERS,
        json={"warehouse_id": warehouse, "statement": sql, "wait_timeout": "50s"},
        timeout=60,
    )
    r.raise_for_status()
    d = r.json()
    statement_id = d["statement_id"]
    while d["status"]["state"] in ("PENDING", "RUNNING"):
        time.sleep(2)
        r = requests.get(
            f"https://{host}/api/2.0/sql/statements/{statement_id}",
            headers=HEADERS, timeout=30,
        )
        r.raise_for_status()
        d = r.json()
    if d["status"]["state"] != "SUCCEEDED":
        raise RuntimeError(f"query failed: {d['status']}")
    return statement_id, d

def fetch_all_rows(statement_id, first_response):
    rows = []
    manifest = first_response.get("manifest", {})
    chunks = manifest.get("chunks", [])
    result = first_response.get("result", {})
    if result.get("data_array"):
        rows.extend(result["data_array"])
    for chunk in chunks:
        idx = chunk["chunk_index"]
        if idx == 0 and result.get("data_array"):
            continue
        r = requests.get(
            f"https://{host}/api/2.0/sql/statements/{statement_id}/result/chunks/{idx}",
            headers=HEADERS, timeout=30,
        )
        r.raise_for_status()
        rows.extend(r.json().get("data_array", []))
    return rows

statement_id, resp = execute(SQL)
rows = fetch_all_rows(statement_id, resp)
print(f"total rows fetched: {len(rows)}")

os.makedirs("brain_corpus", exist_ok=True)

records = [{"timestamp": r[0], "topic": r[1], "insight": r[2], "session": r[3]} for r in rows]
with open("brain_corpus/dump.json", "w") as f:
    json.dump(records, f, indent=2)

with open("brain_corpus/dump.md", "w") as f:
    f.write(f"# workspace.barrot.brain -- full non-error dump ({len(records)} rows)\n\n")
    f.write("Raw, unedited. Generated by scripts/dump_brain_corpus.py.\n\n---\n\n")
    for rec in records:
        f.write(f"## {rec['topic']}\n")
        f.write(f"*{rec['timestamp']} | session {rec['session']}*\n\n")
        f.write(f"{rec['insight']}\n\n---\n\n")

print("wrote brain_corpus/dump.json and brain_corpus/dump.md")
