models:
  - model: google/gemma-2-2b-it
    parameters:
      weight: 0.7
  - model: google/gemma-2-9b-it
    parameters:
      weight: 0.3
merge_method: linear
dtype: bfloat16
tokenizer_source: google/gemma-2-2b-it
