"""
PR Implementation Framework.

Generates well-documented pull request bodies from a list of
Recommendation objects.  When a GitHub token is available the framework
will open real PRs via the GitHub REST API; otherwise it writes the PR
document to .apex_lattice/findings/ for manual review.
"""

from __future__ import annotations

import json
import os
import uuid
from dataclasses import asdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from apex_lattice.audit import AuditTrail
from apex_lattice.recommendations import Recommendation

_FINDINGS_DIR = Path(".apex_lattice") / "findings"


class PRFramework:
    """Creates pull request documents (and optionally real GitHub PRs)."""

    def __init__(
        self,
        cycle_id: str,
        repo: str | None = None,
        base_branch: str = "Main",
        github_token: str | None = None,
        base_dir: Path | None = None,
    ) -> None:
        self.cycle_id = cycle_id
        self.repo = repo or os.environ.get("GITHUB_REPOSITORY", "")
        self.base_branch = base_branch
        self._token = github_token or os.environ.get("GITHUB_TOKEN", "")
        self._base_dir = base_dir or Path(".")
        self._findings_dir = self._base_dir / _FINDINGS_DIR
        self._findings_dir.mkdir(parents=True, exist_ok=True)
        self.audit = AuditTrail(cycle_id, base_dir=self._base_dir)

    # ------------------------------------------------------------------
    def create_prs(self, recommendations: list[Recommendation]) -> list[dict[str, Any]]:
        """Generate PR documents for all recommendations."""
        results: list[dict[str, Any]] = []
        for rec in recommendations:
            result = self._create_pr(rec)
            results.append(result)
        self.audit.log("prs_created", {"count": len(results)})
        return results

    # ------------------------------------------------------------------
    def _create_pr(self, rec: Recommendation) -> dict[str, Any]:
        body = self._build_pr_body(rec)
        pr_doc = {
            "id": f"pr_{uuid.uuid4().hex[:12]}",
            "cycle_id": self.cycle_id,
            "recommendation_id": rec.id,
            "title": f"[Apex Lattice] {rec.title}",
            "body": body,
            "base": self.base_branch,
            "priority": rec.priority,
            "created_at": datetime.now(timezone.utc).isoformat(),
        }

        if self._token and self.repo:
            pr_doc["status"] = self._submit_github_pr(rec, body)
        else:
            pr_doc["status"] = "draft"
            self._persist_pr_doc(pr_doc)

        self.audit.log("pr_created", {"pr_id": pr_doc["id"], "status": pr_doc["status"]})
        return pr_doc

    # ------------------------------------------------------------------
    def _build_pr_body(self, rec: Recommendation) -> str:
        actions_md = "\n".join(f"- {a}" for a in rec.proposed_actions)
        findings_md = "\n".join(f"- `{fid}`" for fid in rec.related_finding_ids)
        return (
            f"## 🔍 Apex Lattice – Infrastructure Improvement Proposal\n\n"
            f"**Cycle ID:** `{rec.cycle_id}`  \n"
            f"**Category:** `{rec.category}`  \n"
            f"**Priority:** {rec.priority} / 5  \n"
            f"**Estimated Effort:** {rec.estimated_effort}  \n"
            f"**Generated:** {rec.created_at}\n\n"
            f"---\n\n"
            f"### Rationale\n\n{rec.rationale}\n\n"
            f"### Proposed Actions\n\n{actions_md}\n\n"
            f"### Related Findings\n\n{findings_md}\n\n"
            f"### Metadata\n\n"
            f"```json\n{json.dumps(rec.metadata, indent=2)}\n```\n\n"
            f"---\n"
            f"*This PR was automatically generated by the Apex Lattice "
            f"analysis pipeline.*\n"
        )

    def _submit_github_pr(self, rec: Recommendation, body: str) -> str:
        """Submit a real PR using the GitHub API.  Returns the PR URL or error."""
        try:
            import urllib.request

            branch_name = (
                f"apex-lattice/{self.cycle_id}/{rec.category}"
            ).lower().replace(" ", "-")

            payload = json.dumps(
                {
                    "title": f"[Apex Lattice] {rec.title}",
                    "body": body,
                    "head": branch_name,
                    "base": self.base_branch,
                    "draft": True,
                }
            ).encode()

            url = f"https://api.github.com/repos/{self.repo}/pulls"
            req = urllib.request.Request(
                url,
                data=payload,
                headers={
                    "Authorization": f"Bearer {self._token}",
                    "Accept": "application/vnd.github+json",
                    "Content-Type": "application/json",
                    "X-GitHub-Api-Version": "2022-11-28",
                },
                method="POST",
            )
            with urllib.request.urlopen(req, timeout=15) as resp:
                data = json.loads(resp.read())
                return data.get("html_url", "submitted")
        except Exception as exc:  # noqa: BLE001
            self.audit.log("pr_submit_error", {"error": str(exc)})
            self._persist_pr_doc({"title": rec.title, "body": body, "cycle_id": self.cycle_id})
            return f"error: {exc}"

    def _persist_pr_doc(self, pr_doc: dict[str, Any]) -> None:
        ts = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        filename = f"{ts}_pr_{pr_doc.get('id', 'doc')}.json"
        path = self._findings_dir / filename
        with path.open("w", encoding="utf-8") as fh:
            json.dump(pr_doc, fh, indent=2, default=str)
